### ISSUE TITLE
VerifyError in GA4GH AlignmentRecord Conversion

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/convert#43]
I am getting this error in both spark 1.3 and 2.1.0. I cannot reproduce it in unit tests. @jpdna have you seen this?

java.lang.VerifyError: class ga4gh.Reads$ReadAlignment$Builder overrides final method setUnknownFields.(Lcom/google/protobuf/UnknownFieldSet;)Lcom/google/protobuf/GeneratedMessage$Builder;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ga4gh.Reads$ReadAlignment.toBuilder(Reads.java:7761)
	at ga4gh.Reads$ReadAlignment.newBuilder(Reads.java:7755)
	at org.bdgenomics.convert.ga4gh.AlignmentRecordToReadAlignment.convert(AlignmentRecordToReadAlignment.java:75)
	at org.bdgenomics.convert.ga4gh.AlignmentRecordToReadAlignment.convert(AlignmentRecordToReadAlignment.java:49)

**Comment by akmorrow13** [comment]
This ended up being a conflict when spark is provided, which includeds protobuf 2.5. Users will have to shade protobuf in order for them to work.

**Comment by heuermh** [comment]
@akmorrow13 Is this still an issue?

**Comment by akmorrow13** [comment]
Nope, it was resolved in Mango https://github.com/bigdatagenomics/mango/pull/374 which shades protobuf.
